# Configuration for Label Actions - https://github.com/dessant/label-actions

issues:
  actions:
    missing-template:
      comment: >
        Please resubmit this issue using the [Config Help issue template](https://github.com/renovatebot/config-help/issues/new?labels=&template=config-help.md&title=).
      close: true
    needs-config:
      comment: >
        Please add your Renovate config to this issue.
      close: false
    needs-logs:
      comment: >
        Please provide DEBUG logs for this problem. Try to include only the relevant lines, e.g. for the particular dependency and/or branch that's relevant.
      close: false
    filter-logs:
      comment: >
        Please do not copy paste your entire unfiltered logs. Go through the logs yourself and paste here only the parts which seem relevant.
    needs-reproduction:
      comment: >
        This needs to be reproduced in a public repository in order to troubleshoot further. Without a reproduction, it won't be possible to answer further.
      close: false
    unclear-description:
      comment: >
        The current description of what you're trying to solve is not clear enough. Please add comments which better explain what you're trying to achieve, what's going wrong, etc.
