# Number of days of inactivity before an issue becomes stale
daysUntilStale: 3
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 5
# Issues with these labels will never be considered stale
staleLabel: pending-closure
exemptLabels:
  - pinned
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed soon if no further activity occurs.
  
  If this question is not done (either you plan to update it or are waiting
  on someone to respond) then please add a comment here to bump it and/or
  get the other person's attention.
  
  We aim to do our best to solve every problem. This bot is here to help us
  clean up issues which are no longer of use to the original poster, and not
  to close anything prematurely, so bump as you need!
